In prompt, arguments can be provided
not 100% working though

diff --git a/ok b/ok
--- a/ok
+++ b/ok
@@ -5,8 +5,8 @@
 ok() {
     function _ok_cmd_usage {
         unset -f _ok_cmd_usage #emulate a "local" function
-        echo 'Usage: ok [ok-options] <number> [script-options..]
-                     ok command [options]
+        echo 'Usage: ok [ok-options] <number> [script-arguments..]
+       ok command [ok-options]
 
 command (use one):
   <number>        Run the <number>th command from the ".ok" file
@@ -16,9 +16,9 @@ command (use one):
   h, help         Show this usage page
 ok-options:
   -v, --verbose   Show more output, most of the time to stderr
-  -:, --pass-args Next options will be passed as <script-options> (see next)
-script-options:
-  ...             These are passed through, when a line is executed
+  -:, --pass-args Next options will be passed as <script-options> (see script-arguments)
+script-arguments:
+  ...             These are passed through, when a line is executed (you can enter these too at the prompt, when used)
 '
         if [[ -n $1 ]]; then
             echo "$1"
@@ -62,7 +62,8 @@ script-options:
 
     # handle command line arguments first
     local re_is_num='^[0-9]+$'
-    local cmd='list'
+    local re_num_begin='^[0-9]+ '
+    local cmd=list
     local line_nr=0
     local once_check=0
     local show_prompt=1
@@ -110,12 +111,18 @@ script-options:
             if [[ $once_check == 0 || ($once_check == 1 && $_OK_LAST_PWD != $(pwd)) ]]; then
                 _ok_cmd_list
                 if [[ $show_prompt == 1 ]]; then
-                    read -p "${_OK_C_PROMPT}${PROMPT}${C_NC}" line_nr
-                    if [[ $line_nr =~ $re_is_num ]]; then
-                        _ok_cmd_run $line_nr "$@"
+                    local prompt_input
+                    read -p "${_OK_C_PROMPT}${PROMPT}${C_NC}" prompt_input
+                    if [[ $prompt_input =~ $re_is_num ]]; then
+                        _ok_cmd_run $prompt_input "$@"
+                    elif [[ $prompt_input =~ $re_num_begin ]]; then
+                        #some bash multi-platform string handling voodoo
+                        line_nr=$(echo "${prompt_input}" | egrep -o '[[:digit:]]+')
+                        args=${prompt_input:${#line_nr}}
+                        _ok_cmd_run $line_nr $args
                     else
                         if [[ $verbose == 1 ]]; then
-                            >&2 echo "ERROR: entered line number '$LINE_NR' is not a number"
+                            >&2 echo "ERROR: entered line number '$line_nr' is not a number"
                         fi
                     fi
                 fi
