Added --verbose option (and fixed -?)

diff --git a/ok b/ok
--- a/ok
+++ b/ok
@@ -12,6 +12,8 @@ command (use one):
   -L, --list-once    Same as list, but only show when pwd is different from previous run
   -p, --list-prompt  Default command. Show the list and wait for prompt (--list and <number> in one command)
   -?, -h, --help     Show this usage page
+options:
+  -v, --verbose      Show more output, most of the time to stderr
 '
         if [[ -n $1 ]]; then
         	echo "$1"
@@ -28,6 +30,10 @@ command (use one):
             echo -e "${C_PROMPT}${PROMPT}${C_COMMAND}${LINE_TEXT}${C_NC}" | sed -E "s/(#.*)\$/${C_COMMENT}\1/1"
             # remove commented lines, and execute that line from the file
             eval $LINE_TEXT
+        else
+            if [[ $verbose == 1 ]]; then
+                >&2 echo "ERROR: entered line number '$LINE_NR' does not exist"
+            fi
         fi
     }
 
@@ -53,6 +59,7 @@ command (use one):
     local once_check=0
     local show_prompt=1
     local usage_error=
+    local verbose=0
     while (( $# > 0 )) ; do
         if [[ $1 =~ $re_is_num ]]; then
             cmd='run'
@@ -64,7 +71,8 @@ command (use one):
                 -l | --list)        cmd=list;;
                 -L | --list-once)   cmd=list; once_check=1;;
                 -p | --list-prompt) cmd=list; show_prompt=1;;
-                -? | -h | --help )  cmd=usage;;
+                -\? | -h | --help)  cmd=usage;;
+                -v | --verbose)     verbose=1;;
                 *)                  cmd=usage; usage_error="Unknown command/option '$1'";;
             esac
         fi
@@ -93,12 +101,22 @@ command (use one):
                     read -p "${_OK_C_PROMPT}${PROMPT}${C_NC}" line_nr
                     if [[ $line_nr =~ $re_is_num ]]; then
                         cmd_run $line_nr
+                    else
+                        if [[ $verbose == 1 ]]; then
+                            >&2 echo "ERROR: entered line number '$LINE_NR' is not a number"
+                        fi
                     fi
                 fi
+            elif [[ $once_check == 1 && $_OK_LAST_PWD == $(pwd) ]]; then
+                echo "The listing for this folder has already been shown"
             fi
         elif [[ $cmd == usage ]]; then
             cmd_usage "$usage_error"
         fi
         export _OK_LAST_PWD=$(pwd)
+    else
+        if [[ $verbose == 1 ]]; then
+            echo "Nothing to do: this folder doesn't have an '.ok' file"
+        fi
     fi
 }
